int _putchar(char c);
void print_alphabet(void);
void ptint_alphabet_x10(void);
int islower(int c);
int isalpha(int c);
int print_sign(int n);
int abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_tablet(void);
int add(int, int);
void print_to_98(int n);
void ptint_times_tablet(int n);
